### ISSUE TITLE
POST not working, 500 error. Not sure how to change column name without breaking backend.

### ISSUE THREAD

**Issue by kfili** [ga-wdi-boston/full-stack-project#550] opened 2016-12-02 21:01 UTC
I get a 500 error when submitting a form on my site that creates an entry to my 'Places' table, in the backend. See console error message in screenshot at bottom, as I could not copy it.

It seems to be because one of my columns is called 'type'. Is there a way to fix it without changing the name of the column? Otherwise what steps / guide do I follow to change it, without destroying my entire backend?

The whole thing works fine If I comment out the 'type' part of the form in my HTML, like so:
```html
<form id="create-place" class="modal-form">
            <div class="form-group">
              <input name="place[name]" type="text" class="form-control" id="create-place-name" placeholder="Enter name of place">
            </div>
            <!-- <div class="form-group">
              <input name="place[type]" type="text" class="form-control" id="create-place-type" placeholder="Type of place. Is it a Restaurant? Bar, Cafe? Bar? Cafe, Restaurant? Taverna?">
            </div> -->
            <div class="form-group">
              <input name="place[location]" type="text" class="form-control" id="create-place-location" placeholder="Enter Lattitude and Longitude, like this: 37.967913, 23.739452">
            </div>
            <div class="form-group">
              <input name="place[address]" type="text" class="form-control" id="create-place-address" placeholder="Address">
            </div>
            <div class="form-group">
              <input name="place[phone]" type="text" class="form-control" id="create-place-phone" placeholder="Phone Number">
            </div>
            <div class="form-group">
              <input name="place[rating]" type="number" min="1" max="5" class="form-control" id="create-place-rating" placeholder="How smoke free is this Place?? 1 - 5 stars">
            </div>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
```

![screen shot 2016-12-02 at 3 41 57 pm](https://cloud.githubusercontent.com/assets/22824118/20849767/300cbbf2-b8a6-11e6-8984-edf9709e03cd.png)

**Comment by kfili** [comment] 2016-12-02 21:14
I removed the below code from the 'create' method in my places controller but it didn't help.
```rb
location: @place
```

**Comment by kfili** [comment] 2016-12-02 21:17
Server error:

Started POST "/places" for ::1 at 2016-12-02 16:09:28 -0500
Processing by PlacesController#create as */*
  Parameters: {"place"=>{"name"=>"a", "type"=>"a", "location"=>"a", "address"=>"a", "phone"=>"3", "rating"=>"1"}}
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)

ActiveRecord::SubclassNotFound (**Invalid single-table inheritance type: a is not a subclass of Place**):
  app/controllers/places_controller.rb:21:in `create'

**Comment by gaand** [comment] 2016-12-02 21:24
The problem is having a column named `type`?  Did you search that error on google?

**Comment by kfili** [comment] 2016-12-02 21:31
[I looked up the error](https://duckduckgo.com/?q=Invalid+single-table+inheritance+%3A+a+is+not+a+subclass+of+Place&atb=v34-6__&ia=qa) and found that ```type``` is indeed a reserved word and should not be used for a column name.

Now onto the second part of the problem, I will look up how to change the column and update this issue accordingly

**Comment by kfili** [comment] 2016-12-02 21:39
found a nicely laid out guide here http://www.korenlc.com/rails-rename-a-databasetable-column/

**Comment by kfili** [comment] 2016-12-02 22:17
I followed the above guide and changed the name of the column.
I also edited the corresponding controller.

Now I get the following error when I navigate to: http://localhost:4741/places
```
NoMethodError in PlacesController#index
undefined method `type' for #<Place:0x007f9ebf4a78c8>
```
```rb
        @places = Place.all

        render json: @places
    end

    # GET /places/1
```

**Comment by raq929** [comment] 2016-12-02 22:18
Did you migrate?

**Comment by kfili** [comment] 2016-12-02 22:19
first time I migrated it didn't work. see error below.

then I replaced ```place``` with ```places``` and migrated again and it seemed to work, see command line output at bottom. Then I migrated again just for good measure.

Heres my command line:
```
~/wdi/projects/map-project-backend (dev)$ bundle exec rails db:migrate
Error: Command 'db:migrate' not recognized
Did you mean: `$ rake db:migrate` ?

Usage: rails COMMAND [ARGS]

The most common rails commands are:
 generate    Generate new code (short-cut alias: "g")
 console     Start the Rails console (short-cut alias: "c")
 server      Start the Rails server (short-cut alias: "s")
 dbconsole   Start a console for the database specified in config/database.yml
             (short-cut alias: "db")
 new         Create a new Rails application. "rails new my_app" creates a
             new application called MyApp in "./my_app"

In addition to those, there are:
 destroy      Undo code generated with "generate" (short-cut alias: "d")
 plugin new   Generates skeleton for developing a Rails plugin
 runner       Run a piece of code in the application environment (short-cut alias: "r")

All commands can be run with -h (or --help) for more information.
~/wdi/projects/map-project-backend (dev)$ bundle exec rake db:migrate
== 20161202215651 RenameColumnTypeinTablePlacetoPlaceType: migrating ==========
-- rename_column(:place, :type, :place_type)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "place" does not exist
: ALTER TABLE "place" RENAME COLUMN "type" TO "place_type"
/Users/zhanina/wdi/projects/map-project-backend/db/migrate/20161202215651_rename_column_typein_table_placeto_place_type.rb:3:in `change'
/Users/zhanina/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/zhanina/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "place" does not exist
: ALTER TABLE "place" RENAME COLUMN "type" TO "place_type"
/Users/zhanina/wdi/projects/map-project-backend/db/migrate/20161202215651_rename_column_typein_table_placeto_place_type.rb:3:in `change'
/Users/zhanina/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/zhanina/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
PG::UndefinedTable: ERROR:  relation "place" does not exist
/Users/zhanina/wdi/projects/map-project-backend/db/migrate/20161202215651_rename_column_typein_table_placeto_place_type.rb:3:in `change'
/Users/zhanina/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/zhanina/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

then I replaced ```place``` with ```places``` and migrated again and it seemed to work, see command line output at bottom. Then I migrated again just for good measure.
```
~/wdi/projects/map-project-backend (dev)$ bundle exec rake db:migrate
== 20161202215651 RenameColumnTypeinTablePlacetoPlaceType: migrating ==========
-- rename_column(:places, :type, :place_type)
   -> 0.0157s
== 20161202215651 RenameColumnTypeinTablePlacetoPlaceType: migrated (0.0159s) =

~/wdi/projects/map-project-backend (dev)$ bundle exec rake db:migrate
~/wdi/projects/map-project-backend (dev)$ 
```

**Comment by kfili** [comment] 2016-12-02 22:33
So I went in my serializer and changed ```type``` to ```place_type``` and that fixed the above problem

When I fully fill out the CREATE form on my site, all the fields work except for place type, which goes down as null.

```
"id": 15,
"name": "d",
"place_type": null,
"location": "a",
"address": "a",
"phone": "1",
"rating": 1
```

**Comment by raq929** [comment] 2016-12-02 22:42
Check your params in the controller.

**Comment by kfili** [comment] 2016-12-02 22:52
the last piece of the puzzle was editing the HTML. I had change the ```name="``` value.

```html
 <input name="place[place_type]" type="text" class="form-control" id="create-place-type" placeholder="Type of place. Is it a Restaurant? Bar, Cafe? Bar? Cafe, Restaurant? Taverna?">
```

**Comment by raq929** [comment] 2016-12-03 00:05
Close the issue please!

**Closed as completed** 2016-12-03 03:37 UTC

**Comment by kfili** [comment] 2016-12-03 03:40
The cause of the problem was the use of a reserved word as a column name.

The solution starts at this comment https://github.com/ga-wdi-boston/full-stack-project/issues/550#issuecomment-264567791
